name: Build and Push on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CI status for this commit
        id: ci_status
        run: |
          STATUS=$(gh run list \
            --workflow="CI" \
            --branch="${GITHUB_REF_NAME}" \
            --json conclusion,headSha \
            | jq -r ".[] | select(.headSha==\"${GITHUB_SHA}\") | .conclusion")
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Fail if CI failed
        if: ${{ steps.ci_status.outputs.status != 'success' }}
        run: |
          echo "CI did not pass for this commit. Exiting."
          exit 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Release Tag
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build --build-arg DATABASE_URL="postgres://root:mysecretpassword@localhost:5432/local" -t rover-ui:$RELEASE_TAG .
          docker tag rover-ui:$RELEASE_TAG ${{ secrets.DOCKER_HUB_USERNAME }}/rover-ui:$RELEASE_TAG
          docker tag rover-ui:$RELEASE_TAG ${{ secrets.DOCKER_HUB_USERNAME }}/rover-ui:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rover-ui:$RELEASE_TAG
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rover-ui:latest
